name: CI&CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: python -m pytest src/ -v
  
  linter:
    needs: tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint specific file
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"

          #FILTER_REGEX_INCLUDE: ^src/main.py$
          #STRIP_DEFAULT_WORKSPACE_FOR_REGEX: true

          CREATE_LOG_FILE: true
          LOG_FILE: report-linter.txt

          DISABLE_ERRORS: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload linter report
        uses: actions/upload-artifact@v4
        with:
          name: report-linter
          path: report-linter.txt
